Handbook
ni/niveristand-custom-device-handbook pull request #8
Opened 2021-05-26 12:51 UTC by cchidean

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-handbook/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-handbook/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

TODO: Include high-level description of the changes in this pull request.

### Why should this Pull Request be merged?

TODO: Justify why this contribution should be part of the project.

### What testing has been done?

TODO: Detail what testing has been done to ensure this submission meets requirements.

2021-08-31 08:40 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +![](images/Picture5.jpg)
We need to replace this image, with:
![image](https://user-images.githubusercontent.com/62251693/131471135-a5f78979-34a0-403d-b89f-e719d485c506.png)

2021-08-31 08:41 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The following image displays a new custom device project that uses these two libraries.
```suggestion
The following image displays a new custom device template project.
```

2021-08-31 08:48 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +For each of the five types of custom devices, you’ll see two VI libraries in the LabVIEW source project: <span style="color:green">*Custom Device API.lvlib*</span> and <span style="color:green">*Cust
```suggestion
For each of the five types of custom devices, in the LabVIEW source project, you’ll see:
* an _NI VeriStand APIs_ Virtual Folder containing two VI libraries: <span style="color:green">*Custom Device API.lvlib*</span> and <span style="color:green">*Custom Device Utility Library.lvlib.*</span>;
* a <span style="color:green">*Custom Device Name Engine.lvlib.*</span> VI library;
* a <span style="color:green">*Custom Device Name Shared.lvlib.*</span> VI library;
* a <span style="color:green">*Custom Device Name System Explorer.lvlib.*</span> VI library.
```

2021-08-31 08:50 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The Custom Device API library contains most of the type definitions, template VIs and LabVIEW API needed to interact with VeriStand data and timing resources. They allow the VI to behave as a native
```suggestion
The Custom Device API library and Custom Device Utility Library contain most of the type definitions, template VIs and LabVIEW API needed to interact with VeriStand data and timing resources. They allow the VI to behave as a native task in the VeriStand Engine.
```

2021-08-31 08:52 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +&nbsp;&nbsp;&nbsp; **Note:** Some of these VIs also appear on the LabVIEW palette in **[VeriStand](https://zone.ni.com/reference/en-XX/help/372846M-01/veristandmerge/vs_ni_veristand_vis_pal/)** » **[
```suggestion
&nbsp;&nbsp;&nbsp; **Note:** Some of these VIs also appear on the LabVIEW palette in **[NI VeriStand](https://zone.ni.com/reference/en-XX/help/372846M-01/veristandmerge/vs_ni_veristand_vis_pal/)** » **[Custom Device API](https://zone.ni.com/reference/en-XX/help/372846M-01/veristandmerge/vs_custom_device_api_vis_pal/)**.
```

2021-08-31 08:53 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The API library contains the custom device’s configuration and real-time engine VIs. These correspond to the configuration and engine VI libraries (or LLBs). The front panel and block diagram of thes
```suggestion
The API library contains the custom device’s configuration and real-time engine VIs. These correspond to the configuration and engine VI libraries (or LLBs). The front panel and block diagram of these VIs are populated with objects from the Custom Device API libraries.
```

2021-08-31 08:56 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The Custom Device Template Tool names the initialization VI <span style="color:green">*<Custom Device Name> Initialization VI.vi.*</span> It runs in the background when the custom device is first add
```suggestion
The niveristand-custom-device-wizard adds the <span style="color:green">*Initialization VI.vi.*</span>. This VI runs in the background when the custom device is first added to the system definition. The initialization page does not run again unless the operator removes and re-adds the custom device.
```

2021-08-31 09:01 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +While you may rename certain objects in the custom device’s LabVIEW Project, it’s important to understand the ramifications of doing so. For example, the Initialization VI is referenced by name in th
```suggestion
While you may rename certain objects in the custom device’s LabVIEW Project, it’s important to understand the ramifications of doing so. For example, the Initialization VI is referenced by name in the custom device XML file. This file is generated when you first run the niveristand-custom-device-wizard. If you rename the Initialization VI after running the wizard, you’ll need to manually change the path to the Initialization VI in the
```

2021-08-31 09:01 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +custom device XML file.
```suggestion
```

2021-08-31 09:05 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The Custom Device Template Tool creates Main Page.vi. After the custom device has been added to the system definition, the main page runs whenever the operator clicks on the custom device’s top-level
```suggestion
The niveristand-custom-device-wizard creates Main Page.vi inside Dynamically Called virtual folder of the System Explorer library. After the custom device has been added to the system definition, the Main Page runs whenever the operator clicks on the custom device’s top-level item in the System Explorer configuration tree. The following image displays the top-level item.
```

2021-08-31 09:07 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The Custom Device Template Tool creates the <span style="color:green">*<Custom Device Name> RT Driver.vi.*</span> This defines the behavior of the custom device on the **[execution host](http://zone.
```suggestion
The niveristand-custom-device-wizard creates the <span style="color:green">*&lt;Custom Device Name&gt; RT Driver.vi.*</span> This defines the behavior of the custom device on the **[execution host](http://zone.ni.com/reference/en-XX/help/372846B-01/veristand/veristand_glossary/#execution_host)**. The RT Driver VI runs on the execution host regardless of the target’s operating system. VeriStand deploys the engine when the operator runs the project from VeriStand or when the system definition is deployed using the VeriStand Execution API.
```

2021-08-31 09:22 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +VeriStand 2009 did not support the VeriStand Engine on VxWorks operating systems. Starting with VeriStand 2010, if you want to support VxWorks targets such as Compact RIO, you must compile the engine
We remove this. Outdated. OSes not supported anymore.
```suggestion
```

2021-08-31 09:27 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +For more information, refer to **Beyond the Template Frameworks**.
We should make the **Beyond the Template Frameworks** visible somehow that is should be a hiperlink in the future. Maybe make it Red and add a note (insert hiperlink) or something, to not forget to connect it when the page is ready.

2021-08-31 09:29 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The Custom Device Template Tool generates an XML file in the template LabVIEW Project. Any properly formatted XML file will be parsed by VeriStand. After the XML file is created by the Custom Device
```suggestion
The niveristand-custom-device-wizard generates an XML file in the template LabVIEW Project. Any properly formatted XML file will be parsed by VeriStand. After the XML file is created by the Custom Device Template Tool, all updates have to be manual.
```

2021-08-31 09:30 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +The custom device XML file does not automatically synchronize with changes to the LabVIEW project. Also, the file does not automatically deploy. You must modify the XML file in the LabVIEW Project di
```suggestion
The custom device XML file does not automatically synchronize with changes to the LabVIEW project. Also, the file does not automatically deploy. You must modify the XML file in the LabVIEW Project directory when making changes. Building the initialization specification overwrites the XML in the <span style="color:green">*&lt;Common Data&gt;\Custom Devices*</span> folder.
```

2021-08-31 09:40 UTC, phutanu requested changes
Please check my above suggestions. Thanks for your patience. :)

2021-09-01 12:37 UTC, WillCawley commented
Hey @phutanu and @cchidean, how close is this PR to being ready to submit? I think it would be easier for me to review the files if I could make my own PR for a tech writer review.

2021-09-01 15:01 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +* a <span style="color:green">*&lt;Custom Device Name&gt; Engine.lvlib.*</span> VI library;
```suggestion
* a <span style="color:green">*&lt;Custom Device Name&gt; Engine.lvlib*</span> VI library;
```

2021-09-01 15:01 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +* a <span style="color:green">*&lt;Custom Device Name&gt; Shared.lvlib.*</span> VI library;
```suggestion
* a <span style="color:green">*&lt;Custom Device Name&gt; Shared.lvlib*</span> VI library;
```

2021-09-01 15:05 UTC, phutanu commented on docs/What_Is_A_Custom_Device.md
> +* an _NI VeriStand APIs_ virtual folder containing two VI libraries: <span style="color:green">*Custom Device API.lvlib*</span> and <span style="color:green">*Custom Device Utility Library.lvlib.*</s
```suggestion
* an _NI VeriStand APIs_ virtual folder containing two VI libraries: <span style="color:green">*Custom Device API.lvlib*</span> and <span style="color:green">*Custom Device Utility Library.lvlib*</span>;
```

2021-09-01 15:26 UTC, merged